name: PHP Unit Tests

on:   
 push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  ./composer.phar install --ignore-platform-reqs

    - name: Run tests
      run: vendor/bin/phpunit
